spring:
  application:
    name: spel
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:spel
    username: sa
    password:
    # initialization-mode: always
  sql:
    init:
      encoding: utf-8

# MyBatis
mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.domain.spel.model

logging.level.com.atoz_develop.mybatissample.repository: TRACE

apps:
  api:
    mapper-id: "'❤❤❤'"